# set the name for the project
name: fw

services:
  client:
    image: netsos/rhit-netsec:latest
    container_name: client
    hostname: client
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      client-subnet:
        ipv4_address: 10.10.0.4
    extra_hosts:
      server: "10.10.1.5"
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      ip route add 10.10.1.0/24 dev eth0 via 10.10.0.10 &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      bash /volumes/fix_depends.sh &&
      tail -f /dev/null
      "

  server:
    image: netsos/rhit-netsec:fw
    container_name: server
    hostname: server
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      server-subnet:
        ipv4_address: 10.10.1.5
    extra_hosts:
      client: "10.10.0.4"
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/setup_telnetd.sh &&
      bash /volumes/check_config.sh &&
      ip route add 10.10.0.0/24 dev eth0 via 10.10.1.10 &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      bash /volumes/fix_depends.sh &&
      tail -f /dev/null
      "

  firewall:
    image: netsos/rhit-netsec:latest
    container_name: firewall
    hostname: firewall
    working_dir: /volumes/
    tty: true
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      client-subnet:
        ipv4_address: 10.10.0.10
      server-subnet:
        ipv4_address: 10.10.1.10
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      bash /volumes/fix_depends.sh &&
      tail -f /dev/null
      "

networks:
  client-subnet:
    name: client-subnet
    ipam:
      config:
        - subnet: 10.10.0.0/24
  server-subnet:
    name: server-subnet
    ipam:
      config:
        - subnet: 10.10.1.0/24
