# set the name for the project
name: lab06

services:
  hostA:
    image: netsos/rhit-netsec:latest
    container_name: hostA
    hostname: hostA
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    sysctls:
      - net.ipv4.ip_forward=0
    networks:
      local-net:
        ipv4_address: 10.10.0.4
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group || true &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec || true &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      tail -f /dev/null
      "

  hostB:
    image: netsos/rhit-netsec:latest
    container_name: hostB
    hostname: hostB
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    sysctls:
      - net.ipv4.ip_forward=0
    networks:
      local-net:
        ipv4_address: 10.10.0.5
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group || true &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec || true &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      tail -f /dev/null
      "

  attacker:
    image: netsos/rhit-netsec:latest
    container_name: attacker
    hostname: attacker
    working_dir: /volumes/
    tty: true
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    sysctls:
      - net.ipv4.ip_forward=0
      - net.ipv4.icmp_echo_ignore_all=1
    networks:
      local-net:
        ipv4_address: 10.10.0.10
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group || true &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec || true &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      tail -f /dev/null
      "

networks:
  local-net:
    name: local-net
    ipam:
      config:
        - subnet: 10.10.0.0/24
